START TRANSACTION;

CREATE TABLE IF NOT EXISTS `career_openings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `slug` varchar(160) NOT NULL,
  `title` varchar(160) NOT NULL,
  `team` varchar(120) DEFAULT NULL,
  `summary` varchar(255) NOT NULL,
  `description` longtext NOT NULL,
  `employment_type` enum('internship','part_time','full_time','contract','volunteer') NOT NULL DEFAULT 'internship',
  `internship_duration` varchar(80) DEFAULT NULL,
  `eligibility_text` text DEFAULT NULL,
  `questions_json` longtext DEFAULT NULL,
  `application_open_at` datetime DEFAULT NULL,
  `application_close_at` datetime DEFAULT NULL,
  `status` enum('draft','published','archived') NOT NULL DEFAULT 'draft',
  `is_public` tinyint(1) NOT NULL DEFAULT 0,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `created_by_admin_id` int(11) DEFAULT NULL,
  `updated_by_admin_id` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_career_openings_slug` (`slug`),
  KEY `idx_career_openings_status_public` (`status`,`is_public`),
  KEY `idx_career_openings_sort` (`sort_order`,`updated_at`),
  KEY `idx_career_openings_window` (`application_open_at`,`application_close_at`),
  KEY `idx_career_openings_created_by` (`created_by_admin_id`),
  KEY `idx_career_openings_updated_by` (`updated_by_admin_id`),
  CONSTRAINT `fk_career_openings_created_by` FOREIGN KEY (`created_by_admin_id`) REFERENCES `admins` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_career_openings_updated_by` FOREIGN KEY (`updated_by_admin_id`) REFERENCES `admins` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `career_applications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(25) NOT NULL,
  `opening_id` int(11) NOT NULL,
  `campus_affiliation` enum('funaab','fummsa','other') NOT NULL DEFAULT 'other',
  `school_name` varchar(160) DEFAULT NULL,
  `level_text` varchar(30) NOT NULL,
  `full_name` varchar(160) NOT NULL,
  `email` varchar(180) NOT NULL,
  `phone` varchar(30) NOT NULL,
  `portfolio_url` varchar(255) DEFAULT NULL,
  `availability_text` varchar(160) DEFAULT NULL,
  `motivation_text` text DEFAULT NULL,
  `willing_to_join` tinyint(1) NOT NULL DEFAULT 1,
  `responses_json` longtext DEFAULT NULL,
  `status` enum('submitted','shortlisted','interview','offer','hired','rejected') NOT NULL DEFAULT 'submitted',
  `assigned_admin_id` int(11) DEFAULT NULL,
  `reviewed_by_admin_id` int(11) DEFAULT NULL,
  `admin_notes` longtext DEFAULT NULL,
  `submitter_ip` varchar(45) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_career_applications_code` (`code`),
  KEY `idx_career_applications_opening_status` (`opening_id`,`status`),
  KEY `idx_career_applications_campus_status` (`campus_affiliation`,`status`),
  KEY `idx_career_applications_assigned_status` (`assigned_admin_id`,`status`),
  KEY `idx_career_applications_email_created` (`email`,`created_at`),
  KEY `idx_career_applications_created` (`created_at`),
  KEY `idx_career_applications_reviewed_by` (`reviewed_by_admin_id`),
  CONSTRAINT `fk_career_applications_opening` FOREIGN KEY (`opening_id`) REFERENCES `career_openings` (`id`),
  CONSTRAINT `fk_career_applications_assigned_admin` FOREIGN KEY (`assigned_admin_id`) REFERENCES `admins` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_career_applications_reviewed_by` FOREIGN KEY (`reviewed_by_admin_id`) REFERENCES `admins` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `career_application_status_history` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `application_id` int(11) NOT NULL,
  `event_type` enum('submitted','status_changed','assignment_changed','note') NOT NULL DEFAULT 'note',
  `from_status` varchar(20) DEFAULT NULL,
  `to_status` varchar(20) DEFAULT NULL,
  `note` text DEFAULT NULL,
  `changed_by_admin_id` int(11) DEFAULT NULL,
  `assigned_admin_id` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_career_application_history_application` (`application_id`,`created_at`),
  KEY `idx_career_application_history_admin` (`changed_by_admin_id`),
  KEY `idx_career_application_history_assigned` (`assigned_admin_id`),
  KEY `idx_career_application_history_event` (`event_type`),
  CONSTRAINT `fk_career_application_history_application` FOREIGN KEY (`application_id`) REFERENCES `career_applications` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_career_application_history_admin` FOREIGN KEY (`changed_by_admin_id`) REFERENCES `admins` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_career_application_history_assigned_admin` FOREIGN KEY (`assigned_admin_id`) REFERENCES `admins` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

COMMIT;